Implement Tasks page
TritonSE/YCW-Green-Home-Application pull request #24
Opened 2021-05-07 01:38 UTC by shravanhariharan2

### Administrative Info
Monday Board ID: 853606148
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Our Changes
- Task Completion Modal
- Task Filtering
- Common Constants

**Note:** for some reason, the dropdowns on the Task Header /  Task completion aren't working on android, but everything else seems to work so feel free to review everything else.

co-authored with @unsoupervised

## Confirmation of Change 

### iOS
<img width="448" alt="Screen Shot 2021-04-29 at 11 46 37 PM" src="https://user-images.githubusercontent.com/37908451/116663698-51357a80-a94c-11eb-806d-ccbc234310f1.png">
<img width="448" alt="Screen Shot 2021-04-29 at 11 46 45 PM" src="https://user-images.githubusercontent.com/37908451/116663701-5266a780-a94c-11eb-8ecc-441f0b5aabaa.png">
<img width="441" alt="Screen Shot 2021-05-06 at 4 38 31 PM" src="https://user-images.githubusercontent.com/37908451/117378048-816ba480-ae89-11eb-82fe-92a4d024791b.png">

### Android
<img width="394" alt="Screen Shot 2021-05-06 at 4 39 19 PM" src="https://user-images.githubusercontent.com/37908451/117378203-c42d7c80-ae89-11eb-8394-c5d3e68da756.png">
<img width="386" alt="Screen Shot 2021-05-06 at 4 39 29 PM" src="https://user-images.githubusercontent.com/37908451/117378206-c55ea980-ae89-11eb-846d-212260005d01.png">
<img width="392" alt="Screen Shot 2021-05-06 at 4 39 37 PM" src="https://user-images.githubusercontent.com/37908451/117378207-c5f74000-ae89-11eb-85e5-7c0ceb2f6b43.png">
<img width="400" alt="Screen Shot 2021-05-06 at 4 39 58 PM" src="https://user-images.githubusercontent.com/37908451/117378208-c7286d00-ae89-11eb-8cf4-e31dd0024834.png">

2021-05-11 05:42 UTC, bobbytatum27 commented
nit: Can the white space of the modal be extended to the bottom of the screen on ios?

2021-05-11 06:05 UTC, bobbytatum27 commented
Can you delete src/test.txt? It's an empty file and by the name, I'm assuming it's not relevant.

2021-05-11 07:14 UTC, bobbytatum27 requested changes
Overall, beautiful work! I left a few comments on things I noticed. Once we've resolved those, I'll approve.

2021-05-11 07:14 UTC, bobbytatum27 commented on src/components/Tasks/TaskHeader/styles.ts
> +    paddingTop: Platform.OS === 'ios' ? 68 : 40,
probably a good place to use the style constants from `src/constants/Sizes.ts`. Also, is 68 the right padding for ios? It seems a bit far down but it could also be a trick on the eyes from the Tab Navigator's empty header.

2021-05-11 07:14 UTC, bobbytatum27 commented on src/components/Tasks/TaskHeader/styles.ts
> +    minHeight: '90%',
The dropdown spacing isn't consistent on ios. Here's a screen cap from my phone. Note the dropdown menus have no space between, making it hard to accurately press.

![IMG_5020](https://user-images.githubusercontent.com/29647534/117769733-ed7f3d00-b1e8-11eb-9f3c-cabfbcc54500.jpeg)

I'm not sure what device the emulator uses, but I'm running expo on an iPhone Xs Max in the photo above.

2021-05-11 07:14 UTC, bobbytatum27 commented on src/contexts/TaskContext.tsx
> +}
This is the same exact type as that found in `src/types/Task.ts`. Is the distinction between names (`TaskData` vs `Task`) important?

2021-05-11 07:14 UTC, bobbytatum27 commented on src/components/Tasks/TaskHeader/index.tsx
> +      <View>
Just wanna check, what's this view's purpose? It seems the styling is done via the outer view w/ `styles.wrapper` and this view wraps the same exact thing (if I tracked closing tags correctly).

2021-05-11 07:26 UTC, sharmaadvay0 requested changes
Great work on this PR!

Here are a few suggestions:

- The top spacing on iOS for the `TASKS` header is too much. Consider moving it up and adding more spacing between the title and description, and description and dropdown.

- The blue color should ideally exceed the SafeAreaView since the status bar should be blue.

- The spacing between the task cards is too much. You can use that space to make sure letters don't hang off the edge like in `Refrigerator`.

- I can scroll the entire page including the header and the tab bar. Consider moving the scroll view to wrap just the view for the task cards.

- I think this PR needs to be rebased with main since now there are conflicts

2021-05-13 23:32 UTC, shravanhariharan2 commented on src/contexts/TaskContext.tsx
> +}
Great catch - there isn't any distinction so I'll remove `TaskData` since `Task` is being used in other places too.

2021-05-13 23:34 UTC, shravanhariharan2 commented on src/components/Tasks/TaskHeader/index.tsx
> +      <View>
I don't believe it has any purpose, so I'll remove that

2021-05-17 05:46 UTC, unsoupervised commented on src/components/Tasks/TaskHeader/index.tsx
> +      <View>
Correct, thanks for the catch @bobbytatum27. Shravan and I were heavily experimenting with the structure earlier and ran through a bunch of iterations to see if the CSS would respond properly. Looks like we'd forgotten to do fully remove any redundancies.

2021-05-30 00:25 UTC, sharmaadvay0 approved these changes
Great work on this PR. 

Here are a few minor suggestions:

- I can't see the last two badges. You should be able to fix this by adding more padding to the scroll component. 
- Sometimes while scrolling through the badges, I can move the entire page which should not be allowed. When this happens, the tab bar expands and the tasks text and filter scroll up. 
- The blue background for the `TASKS` text and the filter should extend to the status bar on iOS. 
- The tasks page takes about 1-2 seconds to show up after the tasks button is clicked for the first time. At some point, we would probably need to show some kind of loading indicator or improve performance.

2021-05-30 04:04 UTC, bobbytatum27 approved these changes
lgtm! thanks for being so diligent with this PR

2021-06-01 22:42 UTC, merged