Support multi-home on the frontend
TritonSE/YCW-Green-Home-Application pull request #38
Opened 2022-02-01 03:13 UTC by lynguyxn

Co-authored-by: Benson Vuong bensonvuong275@gmail.com

### Administrative Info
Monday Board ID: 853606148
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Allow users to add a new home and switch between homes
  - Change current selected home information in settings page
- Filtered recent activity on home main screen to only show the tasks completed by the current selected home
- Filtered tasks for a specific home on task screen 
- Filtered badges for a specific home on badge screen
- NOTE: done on `refactor` backend env

### Testing
How did you confirm your changes worked? 
- Ran `expo start` and manually tested the following user actions:
  - Adding a new home in user profile screen
  - Switching to a different home
  - Changing home information in settings
  - Completing a task for a specific home and confirming the badge or recent activity does not show up for another home

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

Video in TSE google drive: https://drive.google.com/file/d/1D54xlJRzpag-aH8nwXpsJIVUW2ou_dQK/view?usp=sharing

2022-02-05 03:32 UTC, wllmwu requested changes
Couple minor changes for me, otherwise nice work!

2022-02-05 03:32 UTC, wllmwu commented on src/components/AuthContainer.tsx
> +      {console.log(`in auth: ${appState}`)}
Remove log

2022-02-05 03:32 UTC, wllmwu commented on src/components/Profile/SettingsContainer/index.tsx
> +  const curHomeName = homesJSON[currentHome].home.addressLine1.split(' ')[1];
Do we still need the workaround here? It just stringifies `homes` and then parses it back into an object. I'm not sure where the potential undefined might be, maybe when it tries to destructure `const { home } = homesJSON[0]`. Would it still work if we just do `const { home } = userState.homes.items[currentHome]`?

2022-02-05 03:32 UTC, wllmwu commented on src/components/Tasks/TaskCompletionModal/index.tsx
> +        variables: { input: homeResponse },
Currently both `homeResponse` and `userResponse` are created outside of this if statement, then the if statement decides which of them to use. I think we can just create the object inside the if or else statements instead. For example,
```javascript
if (questionIsHome) {
  const result: any = await API.graphql({
    query: createResponse,
    variables: {
      input: {
        homeID: ...
        questionID: ...
        answer: 'Y'
      },
    },
  });
  ...
```

2022-02-05 03:32 UTC, wllmwu commented on src/contexts/UserResponseContext.tsx
> +      },
Remove these hard coded items, they were left over from testing and never got removed. So we should just have
```javascript
  userResponseState: {
    items: [],
  },
```

2022-02-10 03:09 UTC, sharmaadvay0 approved these changes
LGTM! Great work!

2022-02-10 06:00 UTC, wllmwu approved these changes
Looks LGTM to me!

2022-02-15 23:07 UTC, merged