Fix remaining bugs
TritonSE/YCW-Green-Home-Application pull request #39
Opened 2022-02-27 23:54 UTC by wllmwu

### Administrative Info
Monday Board ID: 853606148
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Fade out unanswered badges
- Show badge earned date in detail page
- Remove hardcoded responses
- Show existing values in onboarding dropdowns
- Fix onboarding submission and transitions between app states
- Fix styling so text in settings shows up on Android

### Testing
How did you confirm your changes worked? 
- Tried them a bunch of times

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.
- Try it yourself

2022-02-28 21:54 UTC, sharmaadvay0 requested changes
@wllmwu, great work on resolving many of these bugs.

A couple of things that are left:

- The delete and share buttons are still there on the badge page
- The onboarding flow after signing up still throws an error

2022-02-28 22:24 UTC, wllmwu commented
> * The delete and share buttons are still there on the badge page
> * The onboarding flow after signing up still throws an error

I will address the first point. Badges are still broken for me so I cannot see any of those pages. (I'm on the `devel` environment.)

I fixed the second point and cannot reproduce it.

2022-03-01 07:11 UTC, sharmaadvay0 commented
> I fixed the second point and cannot reproduce it.

@wllmwu Maybe try switching to the refactor environment? I'm not sure what else would specifically cause this issue only for me...

2022-03-01 20:51 UTC, wllmwu commented
> Maybe try switching to the refactor environment? I'm not sure what else would specifically cause this issue only for me...

@sharmaadvay0 Does it work for you on the devel environment? I was under the impression that we had everything we needed on devel and we no longer need refactor.

2022-03-30 06:11 UTC, sharmaadvay0 approved these changes

2022-03-30 06:35 UTC, lynguyxn approved these changes
tested the application flows and everything looks great :) just had a minor comment

2022-03-30 06:35 UTC, lynguyxn commented on amplify/hooks/README.md
> +# Command Hooks
should we leave this `amplify/hooks` folder in the repo? idk why it was created

2022-03-30 06:40 UTC, merged